export const START_LOADING_PLANTS = "START_LOADING_PLANTS";
export const SUCCESSFULLY_LOADED_PLANTS = "SUCCESSFULLY_LOADED_PLANTS";
export const START_ADDING_PLANT = "START_ADDING_PLANT";
export const SUCCESSFULLY_ADDED_PLANT = "SUCCESSFULLY_ADDED_PLANT"
export const START_UPDATING_PLANT = "START_UPDATING_PLANT";
export const SUCCESSFULLY_UPDATED_PLANT = "SUCCESSFULLY_UPDATED_PLANT"
export const START_DELETING_PLANT = "START_DELETING_PLANT"
export const SUCCESSFULLY_DELETED_PLANT = "SUCCESSFULLY_DELETED_PLANT"
export const SET_CURRENT_PLANT = "SET_CURRENT_PLANT";

export const START_LOADING_EVENTS = "START_LOADING_EVENTS"
export const SUCCESSFULLY_LOADED_EVENTS = "SUCCESSFULLY_LOADED_EVENTS"
export const START_ADDING_EVENT = "START_ADDING_EVENT"
export const SUCCESSFULLY_ADDED_EVENT = "SUCCESSFULLY_ADDED_EVENT"
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT"
export const TOGGLE_SHOW_EVENT_FORM = "TOGGLE_SHOW_EVENT_FORM"
export const SUCCESSFULLY_LOADED_EVENTS_BY_PLANT = "SUCCESSFULLY_LOADED_EVENTS_BY_PLANT"

export const START_LOADING_NOTES = "START_LOADING_NOTES"
export const TOGGLE_SHOW_NOTE_FORM = "TOGGLE_SHOW_NOTE_FORM"
export const START_ADDING_NOTE = "START_ADDING_NOTE"
export const SUCCESSFULLY_ADDED_NOTE = "SUCCESSFULLY_ADDED_NOTE"
export const SUCCESSFULLY_LOADED_NOTES_BY_PLANT = "SUCCESSFULLY_LOADED_NOTES_BY_PLANT"



// export const SET_PAGE_TO_WELCOME = "SET_PAGE_TO_WELCOME";
// export const SET_PAGE_TO_SHOW_PLANT = "SET_PAGE_TO_SHOW_PLANT";
// START_DELETING_PLANT,
// SUCCESSFULLY_DELETED_PLANT,