// PLANTS
export const START_CONTACTING_PLANT_SERVER = "START_CONTACTING_PLANT_SERVER";
export const SUCCESSFULLY_LOADED_PLANTS = "SUCCESSFULLY_LOADED_PLANTS";
export const SUCCESSFULLY_ADDED_PLANT = "SUCCESSFULLY_ADDED_PLANT";
export const SUCCESSFULLY_UPDATED_PLANT = "SUCCESSFULLY_UPDATED_PLANT";
export const SUCCESSFULLY_DELETED_PLANT = "SUCCESSFULLY_DELETED_PLANT";
export const SET_CURRENT_PLANT = "SET_CURRENT_PLANT";

// EVENTS
export const START_CONTACTING_EVENT_SERVER = "START_CONTACTING_EVENT_SERVER";
export const SUCCESSFULLY_LOADED_EVENTS = "SUCCESSFULLY_LOADED_EVENTS";
export const SUCCESSFULLY_ADDED_EVENT = "SUCCESSFULLY_ADDED_EVENT";
export const SUCCESSFULLY_LOADED_EVENTS_BY_PLANT = "SUCCESSFULLY_LOADED_EVENTS_BY_PLANT";
export const SUCCESSFULLY_DELETED_EVENT = "SUCCESSFULLY_DELETED_EVENT";
export const SUCCESSFULLY_UPDATED_EVENT = "SUCCESSFULLY_UPDATED_EVENT";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const TOGGLE_SHOW_EVENT_FORM = "TOGGLE_SHOW_EVENT_FORM";

// NOTES
export const START_CONTACTING_NOTE_SERVER = "START_CONTACTING_NOTE_SERVER";
export const SUCCESSFULLY_ADDED_NOTE = "SUCCESSFULLY_ADDED_NOTE";
export const SUCCESSFULLY_LOADED_NOTES_BY_PLANT = "SUCCESSFULLY_LOADED_NOTES_BY_PLANT";
export const SUCCESSFULLY_DELETED_NOTE = "SUCCESSFULLY_DELETED_NOTE";
export const TOGGLE_SHOW_NOTE_FORM = "TOGGLE_SHOW_NOTE_FORM";