export const START_LOADING_PLANTS = "START_LOADING_PLANTS";
export const SUCCESSFULLY_LOADED_PLANTS = "SUCCESSFULLY_LOADED_PLANTS";
export const SET_CURRENT_PLANT = "SET_CURRENT_PLANT";

export const SET_PAGE_TO_WELCOME = "SET_PAGE_TO_WELCOME";
export const SET_PAGE_TO_SHOW_PLANT = "SET_PAGE_TO_SHOW_PLANT";
